timeout: 1800s

options:
  machineType: E2_HIGHCPU_8

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - src/main/docker/Dockerfile.native-multistage
      - -t
      - gcr.io/$PROJECT_ID/nemesis-backend:$BRANCH_NAME
      - .
images:
  - gcr.io/$PROJECT_ID/nemesis-backend:$BRANCH_NAME